### ISSUE TITLE
gpt-cli was working now can't get aichat-cli to work

### ISSUE THREAD

**Issue by vvstubbs** [TheLime1/aichat-cli#41]
Originally i cloned https://github.com/TheLime1/gpt-cli.git and was running gpt_cli.py and it worked great.I did a pull to see if there was any updates and gpt_cli.py was gone! I check the readme.md and all the requirements are met, and the chatcli.py is not in the base directory it's in aichat/ but running it doesn't work! and setup.py fails as it's looking for README.MD.

I realize that you seemed to have merged gpt-cli with aichat-cli but this seem to be not in a stable state. I have been programming in python for some time, for my own needs, and was quite impressed with gpt-cli, I can provide you with trace backs if required, and I have followed your readme.md. My system is running Fedora 38, and has python 3.11

Let me know if I can help or if you can un-confuse and old man.

**Comment by TheLime1** [comment]
Sorry for the confusion!
i renamed the project because there is a pip package that have the name `gptcli`
The `setup.py` was meant for updating the pip package; now to run the program, you need to go inside the `aichat` folder, then run `chatcli.py`.
so :
```
cd aichat
python chatcli.py
```
dont forget to 
```
pip install -r requirements.txt
```
Good Luck ❤️

**Comment by TheLime1** [comment]
@vvstubbs if you have any other problems feel free to reopen this issue :)

**Comment by TheLime1** [comment]
also check this #42
